// resources/js/Pages/Customer/Tickets/Index.tsx
import CustomerLayout from "@/Layouts/CustomerLayout.tsx";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {__} from "@/translation.ts"
import {usePage} from "@inertiajs/react"
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination"

type Props = {
  tickets: {
    current_page: number
    data: Ticket[]
    first_page_url: string
    from: any
    last_page: number
    last_page_url: string
    links: Link[]
    next_page_url: null | string
    path: string
    per_page: number
    prev_page_url: null | string
    to: any
    total: number
  }
}

interface Ticket {
  id: number
  title: string
  description: string
  resolution_notes: string
  contact_method: string
  created_at: string
  updated_at: string
  closed_at: string
}

interface Link {
  url?: string
  label: string
  active: boolean
}

export default function Index() {
  const {tickets} = usePage<Props>().props;

  return (
    <CustomerLayout>
      <div className="flex flex-col gap-4 justify-between">
        <h1 className="text-3xl font-semibold text-slate-950">Tickets</h1>
        <div className="actions hidden">
          <a href="ticketCreateUrl"
             className="btn btn-outline-primary mt-4">
            <span>Create tickets</span>
          </a>
        </div>
        <div>
          <Table>
            <TableCaption>{__('A list of your recent tickets.')}</TableCaption>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">#</TableHead>
                <TableHead>{__('Title')}</TableHead>
                <TableHead>{__('Description')}</TableHead>
                <TableHead>{__('Resolution notes')}</TableHead>
                <TableHead>{__('Contact Method')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {tickets.data.map((ticket) => (
                <TableRow key={ticket.id}>
                  <TableCell className="font-medium">{ticket.id}</TableCell>
                  <TableCell>{ticket.title}</TableCell>
                  <TableCell>{ticket.description}</TableCell>
                  <TableCell>{ticket.resolution_notes}</TableCell>
                  <TableCell>{ticket.contact_method}</TableCell>
                </TableRow>
              ))}
            </TableBody>
            <TableFooter>
              <TableRow>
                <TableCell colSpan={5}>
                  <Pagination>
                    <PaginationContent>

                      <PaginationPrevious
                        className={!tickets.prev_page_url ? 'disabled' : ''}
                        href={tickets.prev_page_url || '#'}
                      >
                        <span>{__('Previous')}</span>
                      </PaginationPrevious>
                      {tickets.links.map((link, index) => (
                        <PaginationItem key={index}>
                          {link.url ? (
                            <PaginationLink isActive={link.active} href={link.url}>{link.label}</PaginationLink>
                          ) : (
                            <PaginationEllipsis>{link.label}</PaginationEllipsis>
                          )}
                        </PaginationItem>
                      ))}
                      <PaginationNext
                        className={!tickets.prev_page_url ? 'disabled' : ''}
                        href={tickets.next_page_url || '#'}
                      >
                        <span>{__('Next')}</span>
                      </PaginationNext>
                    </PaginationContent>
                  </Pagination>
                </TableCell>
              </TableRow>
            </TableFooter>
          </Table>
        </div>
      </div>
    </CustomerLayout>
  )
}

// resources/js/pages/CustomerAccount/Tickets/Index.vue
<script setup>

import Layout from "../Layouts/Dashboard.vue";
import {onMounted, ref} from "vue";
import Pagination from "../../Components/Pagination.vue"
import {Icon} from "../../Icons/index.js";

const props = defineProps({
  sidebar: Object,
  customer: Object,
  tickets: Object,
  ticketCreateUrl: {
    type: String,
    required: true
  }
})
const _pagination = ref({});
onMounted(() => {
  const _customer = props.customer;
  const {data, ...rest} = _customer;
  _pagination.value = rest;
});
</script>

<template>
  <Layout :sidebar="sidebar" :customer="customer">
    <div class="flex flex-wrap md:flex-nowrap justify-between">
      <h1 class="text-3xl font-semibold text-slate-950">Tickets</h1>
      <div class="actions hidden">
        <a
          :href="ticketCreateUrl"
          class="btn btn-outline-primary mt-4">
          <span>Create tickets</span>
          <Icon.SquaresPlus/>
        </a>
      </div>
    </div>
    <div class="flex flex-col">
      <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
          <div class="overflow-hidden">
            <table
              class="min-w-full text-left text-sm font-light text-surface dark:text-white">
              <thead
                class="border-b border-neutral-200 bg-white font-medium dark:border-white/10 dark:bg-body-dark">
              <tr>
                <th scope="col" class="px-6 py-4">#</th>
                <th scope="col" class="px-6 py-4">Title</th>
                <th scope="col" class="px-6 py-4">Description</th>
                <th scope="col" class="px-6 py-4">Resolution notes</th>
              </tr>
              </thead>
              <tbody>
              <tr v-for="item in tickets.data" :key="item.id"
                  class="border-b border-neutral-200 bg-black/[0.02] dark:border-white/10">
                <td class="whitespace-nowrap px-6 py-4 font-medium">
                  {{ item.id }}
                </td>
                <td class="whitespace-nowrap px-6 py-4 font-medium">
                  {{ item.title }}}
                </td>
                <td class="whitespace-nowrap px-6 py-4">
                  {{ item.description }}
                </td>
                <td class="whitespace-nowrap px-6 py-4">
                  {{ item.resolution_notes }}
                </td>
              </tr>
              </tbody>
            </table>
            <Pagination :pagination="_pagination"/>
          </div>
        </div>
      </div>
    </div>
  </Layout>
</template>
