// resources/js/Pages/Pos/CustomerList.tsx
import {ICustomer} from "@/interfaces/ICustomer.ts";
import {Invoice} from "@/interfaces/Invoice.ts";
import React from "react";
import {__} from "@/translation.ts";
import {Accordion, AccordionContent, AccordionItem, AccordionTrigger} from "@/components/ui/accordion.tsx";

export default function CustomerList({customers, onInvoiceSelected, onCustomerSelected}: {
  customers: ICustomer[];
  onInvoiceSelected: React.Dispatch<React.SetStateAction<Invoice | null>>;
  onCustomerSelected: React.Dispatch<React.SetStateAction<ICustomer | null>>
}) {

  return (
    <div className="">
      <h1 className="text-[1.2rem]">{__('Customers')}</h1>
      {customers.length === 0 && <p className="text-sm">{__('No customers found')}</p>}
      <Accordion type="single" collapsible className="w-full">
        {customers.map(customer => (
          <AccordionItem value={`item-${customer.customer_id}`} key={customer.customer_id}>
            <AccordionTrigger
              className={`cursor-pointer flex justify-between items-center `}
              onClick={() => {
                onCustomerSelected(customer);
              }}>
              <span>{customer.full_name}</span>
            </AccordionTrigger>

            <AccordionContent>
              <div className="border-l-4 max-h-[40vh] overflow-y-auto">
                {customer?.invoices?.map((invoice, i) => (
                  <div key={i} className="cursor-pointer hover:bg-gray-50" onClick={() => onInvoiceSelected(invoice)}>
                    <ul className="px-2">
                      <li className="flex justify-between">
                        <dt className="min-w-40">Precio:</dt>
                        <dd>{invoice.total}</dd>
                      </li>
                      <li className="flex justify-between">
                        <dt className="min-w-40">Fecha de Pago:</dt>
                        <dd>{new Date(invoice.due_date).toLocaleDateString()}</dd>
                      </li>
                      <li className="flex justify-between">
                        <dt className="min-w-40">Increment ID:</dt>
                        <dd>{invoice.increment_id}</dd>
                      </li>
                    </ul>
                  </div>
                ))}
              </div>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  )
}

// resources/js/pages/Pos/CustomerList.vue
<template>
  <div>
    <div v-for="customer in customers" :key="customer.customer_id" class="border-b p-4">
      <div @click="toggleCustomerDetails(customer.customer_id)" class="cursor-pointer flex justify-between items-center">
        <span>{{ customer.full_name }}</span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          viewBox="0 0 20 20"
          fill="currentColor"
          :class="{'rotate-180': isOpen(customer.customer_id)}"
        >
          <path
            fill-rule="evenodd"
            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
            clip-rule="evenodd"
          />
        </svg>
      </div>
      <!-- Detalles del cliente -->
      <div v-if="isOpen(customer.customer_id)" class="mt-2 max-h-[40vh] h-auto overflow-y-scroll">
        <div v-for="invoice in customer.invoices" :key="invoice.increment_id" class="p-2 bg-gray-100 mt-2  rounded flex justify-between cursor-pointer">
          <div class="">
            <div>Precio: {{ formatPrice(invoice.total) }}</div>
            <div>Fecha de Pago: {{ new Date(invoice.due_date).toLocaleDateString() }}</div>
            <div>Increment ID: <b>{{ invoice.increment_id }}</b></div>
          </div>
          <button @click="selectInvoice(invoice)" class=" p-2 m-5" title="Processar">
            <span class="inline-block shrink-0 w-6 h-6"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z"></path></svg></span>
          </button>
        </div>

      </div>
    </div>
  </div>
</template>

<script setup>
import {inject, ref} from 'vue';
const props = defineProps(['customers']);
const emit = defineEmits(['invoiceSelected']);
const formatPrice = inject('formatPrice');

const openCustomerIds = ref([]);

const toggleCustomerDetails = (customerId) => {
  if (openCustomerIds.value.includes(customerId)) {
    openCustomerIds.value = openCustomerIds.value.filter(id => id !== customerId);
  } else {
    openCustomerIds.value.push(customerId);
  }
};

const isOpen = (customerId) => {
  return openCustomerIds.value.includes(customerId);
};

const selectInvoice = (invoice) => {
  emit('invoiceSelected', invoice);
};
</script>

<style scoped>
/* Estilos específicos si son necesarios */
</style>
