// resources/js/pages/Pos/InvoiceDetails.vue
<template>
  <div class="invoice">
    <div class="invoice-header mb-4 flex justify-between items-center">
      <h2 class="text-lg font-bold">Detalles de la Factura</h2>
    </div>

    <div class="invoice-body grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
      <!-- Formulario de Detalles de la Factura -->
      <div>
        <label class="block text-gray-600">Nombre de usuario</label>
        <input
          type="text"
          v-model="editableInvoice.userName"
          class="border p-2 rounded w-full"
          readonly
        />
      </div>
      <div>
        <label class="block text-gray-600">Fecha pago</label>
        <input
          type="datetime-local"
          v-model="editableInvoice.paymentDate"
          class="border p-2 rounded w-full"
          readonly
        />
      </div>
      <div>
        <label class="block text-gray-600">Fecha Vencimiento</label>
        <input
          type="date"
          v-model="editableInvoice.dueDate"
          class="border p-2 rounded w-full"
          readonly
        />
      </div>
      <div>
        <label class="block text-gray-600">Forma de pago</label>
        <select v-model="editableInvoice.paymentMethod" class="border p-2 rounded w-full">
          <option value="cash">Efectivo</option>
          <option value="credit">Crédito</option>
          <option value="transfer">Transferencia</option>
        </select>
      </div>
      <div>
        <label class="block text-gray-600">Referencia de Pago</label>
        <input
          type="text"
          v-model="editableInvoice.paymentReference"
          class="border p-2 rounded w-full"
          readonly
          disabled
        />
      </div>

      <div>
        <label class="block text-gray-600">Subtotal</label>
        <input
          type="number"
          v-model="editableInvoice.subtotal"
          class="border p-2 rounded w-full"
          readonly
        />
      </div>
      <div>
        <label class="block text-gray-600">Impuesto</label>
        <input
          type="number"
          v-model="editableInvoice.tax"
          class="border p-2 rounded w-full"
          readonly
        />
      </div>
      <div>
        <label class="block text-gray-600">Total a pagar</label>
        <input
          type="number"
          v-model="editableInvoice.totalToPay"
          class="border p-2 rounded w-full text-green-600"
          readonly
        />
      </div>
      <div>
        <label class="block text-gray-600">Notas</label>
        <textarea
          v-model="editableInvoice.note"
          class="border p-2 rounded w-full"
        ></textarea>
      </div>
    </div>

    <div class="invoice-footer mt-4 flex space-x-4 justify-center">

      <button @click="confirmAndRegisterPayment" v-if="!isPayment"
              class="p-2 bg-blue-500 text-white rounded shadow-md hover:bg-blue-600">
        Guardar Pago
      </button>
      <button @click="attachReceipt" v-if="isPayment"
              class="p-2 bg-green-500 text-white rounded shadow-md hover:bg-green-600">
        Ver recibo
      </button>
      <button @click="cancel" class="p-2 bg-red-500 text-white rounded shadow-md hover:bg-red-600">
        Limpiar
      </button>
    </div>
  </div>
</template>

<script setup>
import {reactive, onMounted, watch, ref} from 'vue';
import axios from "axios";
import Swal from 'sweetalert2';

const emit = defineEmits(['searchCustomers', 'selectedInvoice']); // Define el evento searchCustomers


const props = defineProps(['invoice', 'customer', 'todayBox']);

const editableInvoice = reactive({
  userName: '',
  paymentDate: '',
  dueDate: '',
  paymentMethod: 'cash',
  actionOnPayment: '',
  paymentReference: '',
  note: '',
  subtotal: 0,
  tax: 0,
  totalToPay: 0,
});

const isPayment = ref(false);
const resetEditableInvoice = () => {
  editableInvoice.userName = '';
  editableInvoice.paymentDate = '';
  editableInvoice.dueDate = '';
  editableInvoice.paymentMethod = 'cash';
  editableInvoice.actionOnPayment = '';
  editableInvoice.paymentReference = '';
  editableInvoice.printOption = '';
  editableInvoice.note = '';
  editableInvoice.subtotal = 0;
  editableInvoice.tax = 0;
  editableInvoice.todaytBox = props.todayBox
  editableInvoice.totalToPay = 0;
};

const updateInvoiceData = () => {
  const invoice = props.invoice;
  const customer = props.customer;
  const todayBox = props.todayBox;

  editableInvoice.userName = customer.full_name || '';
  editableInvoice.paymentDate = new Date().toISOString().substring(0, 16);
  editableInvoice.dueDate = invoice.due_date ? invoice.due_date.substring(0, 10) : '';
  editableInvoice.subtotal = parseFloat(invoice.subtotal || 0).toFixed(2);
  editableInvoice.tax = parseFloat(invoice.tax || 0).toFixed(2);
  editableInvoice.totalToPay = parseFloat(invoice.total || 0).toFixed(2);
  editableInvoice.paymentReference = invoice.increment_id || '';
  editableInvoice.todaytBox = todayBox

};

onMounted(() => {
  updateInvoiceData();
});

watch(() => props.invoice, updateInvoiceData, {deep: true, immediate: true});
watch(() => props.customer, updateInvoiceData, {deep: true, immediate: true});

const confirmAndRegisterPayment = () => {
  Swal.fire({
    title: `¿Quieres proceder con el pago usando ${editableInvoice.paymentMethod}?`,
    icon: 'warning',
    showCancelButton: true,
    confirmButtonText: 'Sí',
    cancelButtonText: 'No'
  }).then(async (result) => {
    if (result.isConfirmed) {
      try {
        const response = await axios.post('/invoice/apply-payment',
          editableInvoice
        );
        if (response && response.data) {
          Swal.fire({
            title: 'Pago registrado',
            icon: 'success'
          });
          isPayment.value = true;
          //resetEditableInvoice();
        }
      } catch (error) {
        console.error('Error al registrar el pago:', error);
        Swal.fire('Error', 'No se pudo registrar el pago.', 'error');
      }
    }
  });
};

const attachReceipt = () => {
  console.log('Adjuntar comprobante de pago');
};

const cancel = () => {
  resetEditableInvoice()
  emit('searchCustomers', []);
  emit('selectedInvoice', null);

};
</script>

<style scoped>
.invoice {
  max-width: 800px;
  margin: auto;
}
</style>

// resources/js/Pages/Pos/InvoiceDetails.tsx
import {Invoice} from "@/interfaces/Invoice.ts";
import React, {useState} from "react";
import RenderInvoice from "@/components/RenderInvoice.tsx";
import {__} from "@/translation.ts";
import {DollarSign, LoaderCircle, TriangleAlert} from "lucide-react";
import {Button} from "@/components/ui/button.tsx";
import {Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle} from "@/components/ui/dialog.tsx";
import axios from "axios";
import {ICustomer} from "@/interfaces/ICustomer.ts";
import {usePage} from "@inertiajs/react";
import {TodayBox} from "@/Pages/Pos/MainContentPos.tsx";
import {toast} from "sonner";

type Props = {
  config: {
    currency: string
    currencySymbol: string
    todayBox: TodayBox
  }
}

export default function InvoiceDetails({onSelectedInvoice, invoice, customer}: {
  onSelectedInvoice: React.Dispatch<React.SetStateAction<Invoice | null>>;
  invoice: Invoice;
  customer: ICustomer | null;
}) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const {config} = usePage<Props>().props

  const handleConfirm = () => {
    setOpen(false);
    console.log(invoice, onSelectedInvoice)
    const editableInvoice = {
      paymentMethod: 'cash',
      userName: customer?.full_name || '',
      paymentDate: new Date().toISOString().substring(0, 16),
      dueDate: invoice.due_date ? invoice.due_date.substring(0, 10) : '',
      subtotal: parseFloat(invoice.subtotal || '0').toFixed(2),
      tax: parseFloat(invoice.tax || '0').toFixed(2),
      totalToPay: parseFloat(invoice.total || '0').toFixed(2),
      paymentReference: invoice.increment_id || '',
      todaytBox: config.todayBox,
      printOption: '',
      actionOnPayment: '',
      note: ''
    }

    setLoading(true)
    console.log(editableInvoice)


    axios.post('/invoice/apply-payment', {
      ...editableInvoice
    }).then(res => {
      console.log(res)
      invoice.status = 'paid'
      onSelectedInvoice(invoice)

    }).catch(err => {
      toast.error(err.response.data.message, {
        classNames: {
          icon: 'text-red-500',
          title: 'text-red-500'
        }
      })
    }).finally(() => {
      setLoading(false)
    })
  }
  return (
    <>
      <RenderInvoice invoice={invoice}>
        <Button disabled={!invoice} type="button" onClick={() => setOpen(true)}>
          {!loading ? (
            <>
              <span>{__('Pay')}</span>
              <DollarSign/>
            </>
          ) : <LoaderCircle className="animate-spin"/>}
        </Button>
      </RenderInvoice>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-[400px]">
          <DialogHeader className="flex flex-col items-center gap-2">
            <TriangleAlert size={40}/>
            <DialogTitle>{__('Are you sure to pay?')}</DialogTitle>
          </DialogHeader>
          <DialogFooter className="mt-3">
            <div className="w-full flex justify-center gap-3">
              <Button
                className="px-8 bg-red-50 text-red-500 border-[1px] border-red-100 rounded-lg hover:bg-red-100 hover:underline"
                type="button" onClick={() => setOpen(false)}>{__('Cancel')}</Button>
              <Button
                className="px-8 bg-green-50 text-green-500 border-[1px] border-green-100 rounded-lg hover:bg-green-100 hover:underline"
                type="button" onClick={handleConfirm}>{__('Confirm')}</Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
