// resources/js/Pages/Customer/Authentication/Login.tsx
import {Button} from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {Input} from "@/components/ui/input"
import {Link} from "@inertiajs/react";
import {useForm as inertiaUseForm} from "@inertiajs/react";
import {z} from "zod"
import {useForm} from "react-hook-form"
import {zodResolver} from "@hookform/resolvers/zod";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage
} from "@/components/ui/form.tsx";
import React, {useEffect, useState} from "react";
import {toast} from "sonner";
import {__} from "@/translation.ts"
import {Loader2} from "lucide-react";
import {Eye, EyeOff} from "lucide-react";

const formSchema = z.object({
  email_address: z.string().email({
    message: "The email must be a valid email address."
  }),
  password: z.string().min(3),
})

export default function Login() {
  const {data, post, errors, setData, processing} = inertiaUseForm({
    email_address: "",
    password: "",
  })

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: data,
  })

  const onSubmit = () => {
    post('login');
  }

  useEffect(() => {
    if (errors && "error" in errors) {
      // @ts-ignore
      toast.error(<span className="text-red-500">{errors?.error}</span>, {
        position: "top-right",
        classNames: {
          toast: "bg-red-100",
          title: 'text-red-500',
          icon: "text-red-500",
        }
      })
      form.setError("password", {
        type: "manual",
        message: "",
      });
      form.setError("email_address", {
        type: "manual",
        message: "",
      });
    }
  }, [errors]);

  const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setData({
      ...data,
      [e.target.name]: e.target.value
    })
  }

  const [isVisible, setIsVisible] = useState<boolean>(false);

  const toggleVisibility = () => setIsVisible((prevState) => !prevState);

  return (
    <div className="flex h-[85vh] w-full items-center justify-center px-4">
      <Card className="mx-auto max-w-sm">
        <CardHeader>
          <CardTitle className="text-2xl">{__('Sign In')}</CardTitle>
          <CardDescription>
            {__('Enter your email below to login to your account')}
          </CardDescription>
        </CardHeader>
        <CardContent className="w-full">
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">
              <FormField
                control={form.control}
                name="email_address"
                render={({field}) => (
                  <FormItem>
                    <FormLabel htmlFor="email_address">{__('Email')}</FormLabel>
                    <FormControl>
                      <Input className="" type="email" placeholder="m@example.com" {...field} onInput={handleInput}/>
                    </FormControl>
                    <FormMessage/>
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="password"
                render={({field}) => (
                  <FormItem >
                    <div className="flex items-center">
                      <FormLabel htmlFor="password">{__('Password')}</FormLabel>
                      <Link href="password/reset" className="ml-auto inline-block text-sm underline">
                        {__('Forgot your password?')}
                      </Link>
                    </div>
                    <FormControl>
                      <div className="relative">
                        <Input type={isVisible ? "text" : "password"} placeholder="" {...field} onInput={handleInput}/>
                        <button
                          className="absolute inset-y-0 end-0 flex h-full w-9 items-center justify-center rounded-e-lg text-muted-foreground/80 ring-offset-background transition-shadow hover:text-foreground focus-visible:border focus-visible:border-ring focus-visible:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50"
                          type="button"
                          onClick={toggleVisibility}
                          aria-label={isVisible ? "Hide password" : "Show password"}
                          aria-pressed={isVisible}
                          aria-controls="password"
                        >
                          {isVisible ? (
                            <EyeOff size={16} strokeWidth={2} aria-hidden="true"/>
                          ) : (
                            <Eye size={16} strokeWidth={2} aria-hidden="true"/>
                          )}
                        </button>
                      </div>
                    </FormControl>
                    <FormMessage/>
                  </FormItem>
                )}
              />

              <Button type="submit" className="w-full" disabled={processing}>
                {!processing ? (
                  <>
                    {__('Login')}
                  </>
                ) : (
                  <>
                    <Loader2 className="animate-spin"/>
                    {__('Please wait')}
                  </>
                )}
              </Button>
            </form>
          </Form>

          <div className="mt-4 text-center text-sm">
            {__("Don't have an account?")} {" "}
            <Link href="/customer/register" className="underline">
              {__('Sign Up')}
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// resources/js/pages/CustomerAccount/Authentication/Login.vue
<script setup>
import LayoutAuth from "../Layouts/Auth.vue";
import Input from "../../Components/Input.vue";
import {useForm} from "@inertiajs/inertia-vue3";
import Button from "../../Components/Button.vue";
import {Icon} from "../../Icons/index.js";

const props = defineProps({
  errors: {
    type: Object,
    required: false
  }
})

const form = useForm({
  email_address: null,
  password: null,
});

const submit = () => {
  form.post('login');
}
</script>

<template>
  <LayoutAuth title="Sign in">
    <form class="space-y-5 w-full" @submit.prevent="submit">
      <div v-if="form.errors?.error" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
           role="alert">
        <span class="block sm:inline">{{ form.errors?.error }}</span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg fill="red" @click="() => form.errors.error = false" width="20px" height="20px" viewBox="0 0 24 24"
                 xmlns="http://www.w3.org/2000/svg">
            <path
              d="M12,11.2928932 L16.1464466,7.14644661 C16.3417088,6.95118446 16.6582912,6.95118446 16.8535534,7.14644661 C17.0488155,7.34170876 17.0488155,7.65829124 16.8535534,7.85355339 L12.7071068,12 L16.8535534,16.1464466 C17.0488155,16.3417088 17.0488155,16.6582912 16.8535534,16.8535534 C16.6582912,17.0488155 16.3417088,17.0488155 16.1464466,16.8535534 L12,12.7071068 L7.85355339,16.8535534 C7.65829124,17.0488155 7.34170876,17.0488155 7.14644661,16.8535534 C6.95118446,16.6582912 6.95118446,16.3417088 7.14644661,16.1464466 L11.2928932,12 L7.14644661,7.85355339 C6.95118446,7.65829124 6.95118446,7.34170876 7.14644661,7.14644661 C7.34170876,6.95118446 7.65829124,6.95118446 7.85355339,7.14644661 L12,11.2928932 Z"/>
          </svg>
        </span>
      </div>
      <Input v-model="form.email_address" :required="true" type="email" label="Email Address" id="email" name="email"/>
      <Input v-model="form.password" :required="true" type="password" label="Password" id="password" name="password"/>
      <div class="flex justify-between items-center mt-6 text-sm leading-5">
        <a href="/customer/password/reset" class="underline cursor-pointer opacity-[67%] hover:opacity-[80%]">Forget
          your password?</a>
      </div>
      <Button
        :is-loading="form.processing"
        type="submit"
        class="w-full">
        <span>Continue</span>
        <Icon.LockOpen/>
      </Button>
    </form>
    <div class="mt-3 space-x-0.5 text-sm leading-5 text-left w-full" style="color:#212936">
      <span class="opacity-[47%]"> Don't have an account? </span>
      <a class="underline cursor-pointer opacity-[67%] hover:opacity-[80%]" data-auth="register-link"
         href="/customer/register">
        <span>Sign up</span>
      </a>
    </div>
  </LayoutAuth>
</template>
